# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: aidoku-cli

release:
  prerelease: auto
  draft: false
  name_template: "aidoku-cli v{{.Version}}"

before:
  hooks:
    - go mod tidy
    - sh ./scripts/completions
builds:
  - main: ./cmd/aidoku
    binary: aidoku
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: | 
      -s -w
      -X github.com/Aidoku/aidoku-cli/cmd/aidoku/cmd.version={{.Version}} 
      -X github.com/Aidoku/aidoku-cli/cmd/aidoku/cmd.commit={{.FullCommit}}
      -X github.com/Aidoku/aidoku-cli/cmd/aidoku/cmd.date={{.Date}}
      -X github.com/Aidoku/aidoku-cli/cmd/aidoku/cmd.builtBy=goreleaser
archives:
  - replacements:
      darwin: macos
      386: i386
      amd64: x86_64
    wrap_in_directory: 'false'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - tap:
      owner: beerpiss
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Aidoku/aidoku-cli
    description: Aidoku development toolkit
    commit_msg_template: "{{.ProjectName}}: Update to version {{.Tag}}"
    license: 0BSD
    install: |
      bin.install "aidoku"
      (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
      (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
      (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
    test: |
      system "#{bin}/aidoku --version"

changelog:
  sort: asc
  use: github
  groups:
    - title: "New features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  
nfpms:
  - license: 0BSD
    maintainer: beerpsi <beerpsi@duck.com>
    homepage: https://github.com/Aidoku/aidoku-cli
    bindir: /usr/bin
    description: Aidoku development toolkit
    formats:
    - deb
    - rpm
    - apk
    contents:
    - src: completions/_bash
      dst: /usr/share/bash-completion/completions/aidoku
    - src: completions/_zsh
      dst: /usr/share/zsh/site-functions/_aidoku
    - src: completions/_fish
      dst: /usr/share/fish/vendor_completions.d/aidoku.fish
